/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package search;

import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.layout.AnchorPane;
import javafx.stage.Stage;
import javafx.fxml.FXMLLoader;


public class App extends Application {

    @Override
    public void start(Stage primaryStage) throws Exception {
        // Memuat file FXML
        AnchorPane root = FXMLLoader.load(getClass().getResource("/View/SearchView.fxml"));

        Scene scene = new Scene (root);
        primaryStage.setTitle("Cari Tahu?");
        primaryStage.setScene(scene);
        primaryStage.show();
    }

    public static void main(String[] args) {
        launch(args);
    }
}
